### ISSUE TITLE
PPA/Flatpak

### ISSUE THREAD

**Issue by giovannicaligaris** [d4nj1/TLPUI#31]
Any chance of making a PPA or flatpak for this app?

**Comment by d4nj1** [comment]
Hi,
I definitely have this in mind. Right now I have a working setuptools configuration (setup.py) which already can build debian packages. If you like to build it call:

`python3 setup.py --command-packages=stdeb.command bdist_deb`

There is another open issue #28 which cover the first step for  package building/distribution. Please be patient as project is still not as mature as I want it to be before I release any packages.

**Comment by JaneSmith** [comment]
I also support having a Flatpak for this. It's the new modern standard for application distribution, and the sandboxing would be appreciated.

**Comment by Maryse47** [comment]
It won't be possible to changing tlp settings in flatpak.

**Comment by giovannicaligaris** [comment]
Flatpaks have become very common now and they can be on any distro thanks to Gnome Store.

I think you should host your app on Flathub asap, this is a great app and is hidding in Github.

**Comment by d4nj1** [comment]
I'm currently playing around with Flatpak but struggle a bit because I have dependencies to **tlp** and **tlp-stat** command from the host system. I also need permissions to access the configuration files which will change in TLP 1.3. Building a Flatpak might be delayed until TLPUI has been adopted to TLP 1.3.

**Comment by Maryse47** [comment]
I think there is no way for flatpak to edit root owned config files on host. This sounds like a lost cause.

**Comment by giovannicaligaris** [comment]
It is possible, this app has access to root.

https://flathub.org/apps/details/com.leinardi.gst

I'm not sure how it was implemented though.

**Comment by giovannicaligaris** [comment]
https://gitlab.com/leinardi/gst

**Comment by Ari-El-Uno** [comment]
There is an unofficial PPA from Linux Uprising: https://www.linuxuprising.com/2018/11/install-tlpui-in-ubuntu-or-linux-mint.html

**Comment by 3xp4n** [comment]
Any news about tlpui being implemented in Flatpak? I use fedora and it wouldn't hurt to have this option for nonDEB distros

**Comment by d4nj1** [comment]
@3xp4n I hear you. :sweat_smile:
I am still in an initial script state, so nothing done yet. I can't give you more than a "_please be patient_" at the moment.

**Comment by 3xp4n** [comment]
> @3xp4n I hear you. 
> I am still in an initial script state, so nothing done yet. I can't give you more than a "_please be patient_" at the moment.

Of course, thanks for the reply.
I'm waiting :)

**Comment by d4nj1** [comment]
@giovannicaligaris @JaneSmith @3xp4n 
I added a first version of Flatpak scripts. It would be nice if someone would try to build and run it on their machines. Reporting back if UI works or issues appear would be nice.
Documentation for building/installing and the features/limitations can be found here:

https://github.com/d4nj1/TLPUI/tree/master/flatpak

**Comment by d4nj1** [comment]
@giovannicaligaris @JaneSmith @3xp4n
I just added support for everything that was missing before.
So executing tlp-stat on host and also writing configuration files should be working now. Please report if any issues found.

Thanks in advance

**Comment by proletarius101** [comment]
>  I added a first version of Flatpak scripts. It would be awesome if someone would try to build and run it on their machines. Reporting back if UI works or issues appear would be nice.

Are you interested in publishing it to Flathub? I have some experience in doing that and is capable to help if you'd like to.

**Comment by d4nj1** [comment]
@proletarius101
Thanks for the offer but I think I will get it done myself. I would appreciate if you could build and test the Flatpak as described in the [README.md](https://github.com/d4nj1/TLPUI/blob/master/flatpak/README.md).

**Comment by gdonval** [comment]
Just one thing: I believe you can ditch the `--filesystem=host` in your flatpak config and instead use `--filesystem=/etc/tlp.conf` and/or `--filesystem=/etc/tlp.d`.

Also, just a general comment: it is certainly not neat to require dependencies out of the flatpak itself (because flatpak has no way to track them). The correct way would be bundling tlp with the app and run the daemon from there (with correct whitelisting of the `/sys` files. I am not saying that to stop you: having something that works is great, even if it's not perfect. However please keep in mind silently depending on host binaries is generally a bad idea.

**Comment by Perkolator** [comment]
I hope PPA is also considered. Snap/Flatpak isn't an option for some because updating happens silently in background (and, if I have understood correctly, e.g. Mint, updates Flatpaks only slightly after boot... what about users who mainly use sleep&/hibernate and reboot only when absolutely necessary?), and without requiring any credentials. I don't understand who would want such a system to their machines and give away the control, and not knowing when and what has been added/modified/removed from their software.

**Comment by proletarius101** [comment]
> Snap/Flatpak isn't an option for some because updating happens silently in background

Well, that's optional

> and without requiring any credentials

... because you grant the permission with you credentials?

>  Mint, updates Flatpaks only slightly after boot... what about users who mainly use sleep&/hibernate and reboot only when absolutely necessary?

The vendor updater is a systemd timer, so it's not true

**Comment by Perkolator** [comment]
> Well, that's optional

What is optional? Flatpaks/Snaps automatically updates silently in the background.

> ... because you grant the permission with you credentials?

When an update to Flatpaks/Snaps is installed, at what point of the silent update process user is asked for confirmation and his/her password?

> The vendor updater is a systemd timer, so it's not true

I don't understand what you mean by vendor updater, and googling doesn't reveal anything on the matter. I only see Flatpak updates activated after a boot in Mint 20 ("systemd[1]: Starting flatpak system helper..."). In Mint there's a "Apply Flatpak updates" startup application.

Here's [Flatpak software management](https://forums.linuxmint.com/viewtopic.php?t=260872) topic in Mint forums, from there:

> automatically by the flatpak updater service that runs 10 minutes after every boot

(later message from the same user corrects this to 20 seconds after every boot)

>> Is the flatpak updater service something that runs silently in the background? Is it separate from the normal Update Manager? And updates are automatically downloaded and installed without prompting by the user (essentially forced silent updates)?

> Yes, yes and ... yes

One user asks a very good question:

> How do we go from having to enter a password to install updates to having auto updates that don't inform the user that the process is running or when it is through?

There's more cons to Flatpak/Snap than these (e.g. trusting Flatpak devs updating dependencies with security fixes?).. the idea is good but there's IMO just too many cons. Hence my vote for PPA.

**Comment by gdonval** [comment]
Please, this is not a forum but an issue tracker. If you have any concerns like this, find another platform to voice them. In this case, providing a PPA or a Flatpak are perfectly orthogonal: providing a Flatpak won't impede the release of a PPA (nor vice-versa).

Update points are moot: **overridable** *defaults* in a *specific distribution* are not really compelling reasons to choose anything in particular. I insist on *overridable*: every single of your concerns can be addressed by trivial configuration. Again if you want to discuss this further (to get some guidance, etc.), find an appropriate place (this is not).

**Comment by Perkolator** [comment]
This issue topic is "PPA **OR** Flatpak" and I only see talk about Flatpak, not PPA. I've seen many times how a developer chooses just one method of distributing software so I wanted to add my measly vote of implementing PPA, and shortly explain why. Take it or leave it.

**Comment by d4nj1** [comment]
Hi @gdonval @proletarius101 and @Perkolator ,
in my opinion there is no "PPA **OR** Flatpak". I think both have their pros and cons and I have the wish to support both of them. Most of the posts in this thread are about Flatpak because I did not concentrate so much on creating a PPA as there is already one for Ubuntu provided by [linuxuprising](https://github.com/d4nj1/TLPUI/wiki/Install-instructions#ubuntu-ppa-with-prebuild-packages-third-party). Furthermore there is also a description in the docs on how to build a debian package.
Maybe I will close this issue and create sperate ones for PPA and Flatpak. Then there should be no discussion around what to support and why.

I hope that is in everybodies interest.

**Comment by d4nj1** [comment]
Please continue discussion/suggestions in the newly created issues.
