### ISSUE TITLE
Add item type "integer" with range

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#8]
Situation: items of type integer are implemented as pure text "entry".

Problems of the current approach:
* User can save invalid entries

Solution:
* New type "integer" with attributes "range_min", "range_max"

Suggestion:
* Spin button +1/-1

**Comment by d4nj1** [comment]
There already exists a "numeric" type to be set in JSON schema.
See **START_CHARGE_THRESH_BAT0** or **CPU_MIN_PERF_ON_AC** for an example.

```
{
"type": "numeric",
"values": "1-96",
}
```

Not all numeric config values have a proper min/max value pre defined. Range missing for:
* DISK_IDLE_SECS_*
* MAX_LOST_WORK_SECS_*
* CPU_SCALING_*_FREQ_*
* CPU_*_PERF_*

Shell we add a range anyway to prevent user misconfiguration?

**Comment by linrunner** [comment]
What about "open" ranges? E.g. 

* "values": "1-"
* "values": "-99"

**Comment by d4nj1** [comment]
I made an effort on open ranges but finally gave up now because it seems that all Gtk3-objects for this purpose require pre defined ranges.
I tried it with GtkSpinButton and even with a GtkScale slider but had no success. I could allow open ranges in schema, but then I have to set some "min" and "max" value hardcoded. I don't think that this would be a good solution.

I keep it like this for now. Please open issue again if not satisfied with this answer or solution identified.

**Comment by linrunner** [comment]
OK :-)
