### ISSUE TITLE
Option SOUND_POWER_SAVE_ON_* Do not let me set timeout in sec

### ISSUE THREAD

**Issue by mozlima** [d4nj1/TLPUI#83]
Option:
SOUND_POWER_SAVE_ON_AC
SOUND_POWER_SAVE_ON_BAT
Should accept number instead of only 0 or 1

\# DOC
https://www.kernel.org/doc/html/latest/sound/designs/powersave.html

\# TLP DOC
\# Enable audio power saving for Intel HDA, AC97 devices (timeout in secs).
\# A value of 0 disables, >=1 enables power saving (recommended: 1).
\# Default: 0 (AC), 1 (BAT)

**Comment by d4nj1** [comment]
Hi @mozlima and thanks for the request.
I think you are totally right with your suggestion.

kernel.org also suggest to not set **1** as minimum but **10** 
`Setting this to 1 (the minimum value) isn’t recommended because many applications try to reopen the device frequently. 10 would be a good choice for normal operations.`

@linrunner What do you think? Should the battery default maybe changed to 10 seconds as a default in future? What do you think would be a sane max value?

Kind regards

**Comment by linrunner** [comment]
Hi, in fact, someone else made the same argument - based on the kernel docs - in 2017. But a dev on the pulseaudio-discussion mailing list recommended against it for pulseaudio, so i reverted the change. I see no reason to change it again. The kernel documentation is just the theory, the argument from userspace weighs heavier for me.

https://github.com/linrunner/TLP/commit/7ec4f166d798150eae9320929a3f5a469d101557

Of course you should allow values > 1. I have no opinion on the maximum value.

**Comment by d4nj1** [comment]
Thanks for fast response and the enlightenment @linrunner 
I will change the setting to be numeric and 3600 seconds (60 min) as a maximum for now. Furthermore I will adjust the description for the configuration item in the UI.
Next time I try to look it up for existing issues/requests/commits in the [TLP project](https://github.com/linrunner/TLP) first.

Cheers and have a good start in 2021

**Comment by d4nj1** [comment]
Hi @mozlima 
changes are in latest master now. If anything else missing please don't hesitate to raise another isssue.

Best regards
