### ISSUE TITLE
Provide Flatpak

### ISSUE THREAD

**Issue by d4nj1** [d4nj1/TLPUI#89]
To use a distribution independent package of TLPUI it would be great to have a Flatpak provided by the package maintainer.
Some former discussion has already happened in #31 and current state is [here](https://github.com/d4nj1/TLPUI/tree/master/flatpak).

**Comment by sm-moshi** [comment]
`flatpak-builder --force-clean --user --install-deps-from flathub --install build-dir com.github.d4nj1.tlpui.json
Dependency Sdk: org.gnome.Sdk 3.38
Updating org.gnome.Sdk/x86_64/3.38
Nothing to do.
Dependency Runtime: org.gnome.Platform 3.38
Installing org.gnome.Platform/x86_64/3.38 from flathub
Installing runtime/org.gnome.Platform/x86_64/3.38
Error: Failed to install org.gnome.Platform: Failed to read commit 5db3e872d74f5d79364695df73febcff532fe5ed586d0827cf1b98ddb6fb6c9c: No such metadata object e6ed641c6dda172b7be82a9a2ac14f1c28b74432fa28d5c35062b0b508c30186.dirtree`

Building a local flatpak does not work at the moment, because flatpak keeps throwing a metadata error at me. Only happens with gnome.Plattform 3.38.

**Comment by d4nj1** [comment]
Hi @sm-moshi ,
sadly I am not able to reproduce your issue. For me the platform dependency doe get installed normally:
```
Installing runtime/org.gnome.Sdk/x86_64/3.38
Dependency Runtime: org.gnome.Platform 3.38
Installing org.gnome.Platform/x86_64/3.38 from flathub
Installing runtime/org.gnome.Platform.Locale/x86_64/3.38
Installing runtime/org.gnome.Platform/x86_64/3.38
```

**Comment by LordTermor** [comment]
Can we publish it via flathub or so? I believe it's possible to implement an automatic deployment using GitHub Actions.

**Comment by d4nj1** [comment]
Sorry for the late reply. I currently have nearly no spare time to invest in this project. My private and work life are currently too resource consuming. I can give you no date when I am able to continue here.

Long story short. @LordTermor I think this should be easily doable.

**Comment by oryband** [comment]
any updates? lets release this! ubuntu 22.04 jammy has no release file in the current linuxuprising ppa

**Comment by d4nj1** [comment]
I created a [PR](https://github.com/flathub/flathub/pull/3348) for Flathub but there still exist some glitches to be fixed.

**Comment by d4nj1** [comment]
Flatpak has been released on Flathub, please report any bug findings.

https://flathub.org/apps/details/com.github.d4nj1.tlpui

**Comment by oryband** [comment]
After installing from official flatpak, I get a popup error saying TLP is not installed, even though it is. I'm on Ubunut 22.04

**Comment by d4nj1** [comment]
Please have a look at #110

**Comment by oryband** [comment]
ty!
